language: python
sudo: false
cache:
  pip: true
  directories:
    - $TRAVIS_BUILD_DIR/buildout-cache
python:
  - 2.7
addons:
  apt:
    packages:
    - build-essential
    - gcc
    - python-dev
    - git-core
    - libffi-dev
    - libpcre3
    - libpcre3-dev
    - autoconf
    - libtool
    - pkg-config
    - zlib1g-dev
    - libssl-dev
    - libexpat1-dev
    - libxslt1.1
    - gnuplot
    - libcairo2
    - libpango1.0-0
    - libgdk-pixbuf2.0-0
before_script:
  - export DISPLAY=99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/buildout-cache/{eggs,downloads}
  - echo "[buildout]" > $TRAVIS_BUILD_DIR/default.cfg
  - echo "download-cache = $TRAVIS_BUILD_DIR/buildout-cache/downloads" >> $TRAVIS_BUILD_DIR/default.cfg
  - echo "eggs-directory = $TRAVIS_BUILD_DIR/buildout-cache/eggs" >> $TRAVIS_BUILD_DIR/default.cfg
install:
  - $TRAVIS_BUILD_DIR/bin/buildout -N -t 3 -c $TRAVIS_BUILD_DIR/travis.cfg
script:
  - $TRAVIS_BUILD_DIR/bin/test
