language: python
sudo: required
# dist: xenial
cache:
  pip: true
  directories:
    - $TRAVIS_BUILD_DIR/buildout-cache
python:
  - 2.7
addons:
  apt:
    packages:
      - libpcre3
      - libpcre3-dev
      - libssl-dev
      - libexpat1-dev
      - gnuplot
      - libgdk-pixbuf2.0-0
      - libappindicator1
      - fonts-liberation
      - chromium-browser
      - chromium-chromedriver
before_script:
  ###
  - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d /usr/bin
  - sudo chmod u+x /usr/bin/chromedriver
  - export CHROME_BIN=chromium-browser
  ###
  - export DISPLAY=99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/buildout-cache/{eggs,downloads}
  - echo "[buildout]" > $TRAVIS_BUILD_DIR/default.cfg
  - echo "download-cache = $TRAVIS_BUILD_DIR/buildout-cache/downloads" >> $TRAVIS_BUILD_DIR/default.cfg
  - echo "eggs-directory = $TRAVIS_BUILD_DIR/buildout-cache/eggs" >> $TRAVIS_BUILD_DIR/default.cfg
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout
install:
  - bin/buildout -N -t 3 -c travis.cfg
script:
  # - bin/test -m bika.lims --layer=bika.lims.testing.BikaTestingLayer:Functional
  - bin/test -s bika.lims
